---
title: CfA Hurricane Response
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: email@hurricane-response.org
description: No One's Coming - It's Up to Us
repository: opensavannah/response-theme
baseurl: ''
url: ''
help_url: https://www.codeforamerica.org
logo: https://avatars0.githubusercontent.com/u/43193416?s=400&u=8e1d97c94fa7a9611c8b8fa765e68c8fe86e2e7c
txtbot_trigger: Hurricane
textbot_display: 898211
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
mapbox_access_token: pk.eyJ1IjoibWlrbGItYzR0YiIsImEiOiJjam5kOGg3c2kwMDB3M3dwYXQyMDJpdzFtIn0.yKOyo193qF1quWsNwiFzug
