---
title: Chatham Shelter Response
timezone: America/Indiana/Indianapolis
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: fellowship@opensavannah.org
description: Sea-level-rise is a matter of environmental justice.
repository: opensavannah/response-theme
baseurl: https://github.com/opensavannah/response-theme
url: https://github.com/opensavannah/response-theme
help_url: https://www.codeforamerica.org
logo: https://avatars0.githubusercontent.com/u/43193416?s=400&u=8e1d97c94fa7a9611c8b8fa765e68c8fe86e2e7c
txtbot_trigger: sealevel
textbot_display: 898211
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
mapbox_access_token: pk.eyJ1IjoibWlrbGItYzR0YiIsImEiOiJjam5kOGg3c2kwMDB3M3dwYXQyMDJpdzFtIn0.yKOyo193qF1quWsNwiFzug
